import { reportReasons } from '@/constants/safety';
import { palette } from '@/constants/theme';
import { useAuth } from '@/context/auth-context';
import { useEvents } from '@/context/event-context';
import { SafetyReportReason } from '@/types/event';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function ReportScreen() {
  const params = useLocalSearchParams<{ eventId?: string; messageId?: string; targetUserId?: string; targetName?: string; targetContentLabel?: string }>();
  const { user } = useAuth();
  const { submitSafetyReport, toggleBlockUser, blockedUsers, profile } = useEvents();
  const [reason, setReason] = useState<SafetyReportReason | null>(null);
  const [details, setDetails] = useState('');
  const alreadyBlocked = Boolean(params.targetName && blockedUsers.some((blocked) => params.targetUserId ? blocked.userId === params.targetUserId : blocked.name === params.targetName));
  const isSelf = params.targetUserId ? params.targetUserId === user?.id : params.targetName?.trim().toLowerCase() === profile.name.trim().toLowerCase();
  const [block, setBlock] = useState(alreadyBlocked);
  const [submitting, setSubmitting] = useState(false);
  const submit = async () => {
    if (isSelf) return Alert.alert('自分自身は通報できません');
    if (!reason) return Alert.alert('通報理由を選択してください');
    setSubmitting(true);
    const error = await submitSafetyReport({ eventId: params.eventId, messageId: params.messageId, targetUserId: params.targetUserId, targetUserName: params.targetName, reason, details: details.trim() || undefined });
    setSubmitting(false);
    if (error) return Alert.alert('通報を送信できませんでした', error);
    if (params.targetName && block !== alreadyBlocked) toggleBlockUser(params.targetName, params.targetUserId);
    Alert.alert('通報を受け付けました', '運営者が内容を確認します。通報したことは相手へ通知されません。', [{ text: '閉じる', onPress: () => router.back() }]);
  };
  return <SafeAreaView style={styles.safe} edges={['bottom']}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={styles.content} automaticallyAdjustKeyboardInsets keyboardShouldPersistTaps="handled" keyboardDismissMode={Platform.OS === 'ios' ? 'interactive' : 'on-drag'}><View style={[styles.notice, isSelf && styles.selfNotice]}><Ionicons name={isSelf ? 'alert-circle-outline' : 'eye-off-outline'} size={20} color={isSelf ? palette.danger : palette.primary} /><Text style={[styles.noticeText, isSelf && styles.selfNoticeText]}>{isSelf ? '自分自身を通報・ブロックすることはできません。前の画面へ戻って対象者を確認してください。' : '通報者の情報は相手に表示されません。虚偽の通報はしないでください。'}</Text></View>{params.targetContentLabel && <View style={styles.target}><Text style={styles.targetLabel}>対象の内容</Text><Text style={styles.targetName}>{params.targetContentLabel}</Text></View>}{params.targetName && <View style={styles.target}><Text style={styles.targetLabel}>対象の利用者</Text><Text style={styles.targetName}>{params.targetName}{isSelf ? '（自分）' : ''}</Text></View>}<Text style={styles.label}>通報理由</Text><View style={styles.reasons}>{reportReasons.map((item) => <TouchableOpacity key={item.value} accessibilityRole="radio" accessibilityState={{ selected: reason === item.value }} style={[styles.reason, reason === item.value && styles.reasonSelected]} onPress={() => setReason(item.value)} disabled={isSelf || submitting}><View style={[styles.radio, reason === item.value && styles.radioSelected]}>{reason === item.value && <View style={styles.radioDot} />}</View><Text style={[styles.reasonText, reason === item.value && styles.reasonTextSelected]}>{item.label}</Text></TouchableOpacity>)}</View><Text style={styles.label}>詳しい内容（任意）</Text><TextInput style={styles.details} value={details} onChangeText={setDetails} editable={!isSelf && !submitting} multiline maxLength={1000} placeholder="いつ、どのような問題があったか記載してください" placeholderTextColor="#9AA39E" /><Text style={styles.count}>{details.length}/1,000</Text>{params.targetName && !isSelf && <View style={styles.block}><View style={styles.blockCopy}><Text style={styles.blockTitle}>{params.targetName}さんをブロック</Text><Text style={styles.blockText}>今後この利用者のメッセージを表示しません</Text></View><Switch value={block} onValueChange={setBlock} disabled={submitting} /></View>}</ScrollView><View style={styles.bottom}>{isSelf ? <TouchableOpacity style={styles.back} onPress={() => router.back()}><Text style={styles.backText}>前の画面へ戻る</Text></TouchableOpacity> : <TouchableOpacity accessibilityRole="button" style={[styles.submit, submitting && styles.submitDisabled]} onPress={submit} disabled={submitting}>{submitting ? <ActivityIndicator color={palette.surface} /> : <><Ionicons name="flag" size={18} color={palette.surface} /><Text style={styles.submitText}>通報を送信</Text></>}</TouchableOpacity>}</View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.canvas }, flex: { flex: 1 }, content: { padding: 20, paddingBottom: 30 }, notice: { flexDirection: 'row', borderRadius: 17, backgroundColor: palette.primarySoft, padding: 14 }, noticeText: { flex: 1, color: palette.primary, fontSize: 13, lineHeight: 19, marginLeft: 9 }, selfNotice: { backgroundColor: '#FCEDEE' }, selfNoticeText: { color: palette.danger }, target: { borderRadius: 17, backgroundColor: palette.surface, padding: 15, marginTop: 12 }, targetLabel: { color: palette.muted, fontSize: 12 }, targetName: { color: palette.ink, fontSize: 15, fontWeight: '900', marginTop: 4 }, label: { color: palette.ink, fontSize: 14, fontWeight: '900', marginTop: 22, marginBottom: 10 }, reasons: { gap: 7 }, reason: { minHeight: 48, flexDirection: 'row', alignItems: 'center', borderRadius: 15, backgroundColor: palette.surface, paddingHorizontal: 14, borderWidth: 1, borderColor: palette.line }, reasonSelected: { backgroundColor: palette.primarySoft, borderColor: palette.primary }, radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#A7B0AB', alignItems: 'center', justifyContent: 'center', marginRight: 10 }, radioSelected: { borderColor: palette.primary }, radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: palette.primary }, reasonText: { color: palette.ink, fontSize: 12, fontWeight: '700' }, reasonTextSelected: { color: palette.primary }, details: { minHeight: 115, borderRadius: 17, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.line, padding: 14, color: palette.ink, fontSize: 12, textAlignVertical: 'top' }, count: { color: palette.muted, fontSize: 12, textAlign: 'right', marginTop: 5 }, block: { flexDirection: 'row', alignItems: 'center', borderRadius: 17, backgroundColor: palette.surface, padding: 15, marginTop: 17 }, blockCopy: { flex: 1, marginRight: 12 }, blockTitle: { color: palette.ink, fontSize: 12, fontWeight: '800' }, blockText: { color: palette.muted, fontSize: 12, marginTop: 4 }, bottom: { padding: 14, backgroundColor: palette.surface, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.line }, submit: { minHeight: 54, borderRadius: 17, backgroundColor: palette.accent, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' }, submitDisabled: { opacity: 0.6 }, submitText: { color: palette.surface, fontSize: 14, fontWeight: '900', marginLeft: 7 }, back: { minHeight: 54, borderRadius: 17, backgroundColor: palette.primary, alignItems: 'center', justifyContent: 'center' }, backText: { color: palette.surface, fontSize: 14, fontWeight: '900' },
});
